In [ ]:
import pandas as pd

# DATA CLEANING

# Drop Null values

In [ ]:
df=pd.read_csv("/content/data - data.csv")

In [ ]:
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df.shape

(169, 4)

In [ ]:
# drop null values in df
new_df=df.dropna()

In [ ]:
print(new_df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [ ]:
print(new_df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
new_df.shape

(164, 4)

In [ ]:
new_df["Maxpulse"]

0      130
1      145
2      135
3      175
4      148
      ...
164    140
165    145
166    145
167    150
168    150
Name: Maxpulse, Length: 164, dtype: int64

In [ ]:
# Drop null values with changing the original dataset
df.dropna(inplace=True)

In [ ]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [ ]:
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

# Replace Null values

In [ ]:
df1=pd.read_csv("/content/data - data.csv")
print(df1.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df2=df1.fillna(50)

In [ ]:
print(df2.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112      50.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132      50.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137      50.0
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125      50.0
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127      50.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
# change the original dataset
df1.fillna(100,inplace=True)
print(df1.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     100.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132     100.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137     100.0
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125     100.0
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127     100.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
# fill the null value only in one column
df1["Calories"].fillna(150,inplace=True)
print(df1.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     100.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132     100.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137     100.0
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125     100.0
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127     100.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

# Replacing null values using meam, median, mod

In [ ]:
x=pd.read_csv("/content/data - data.csv")

In [ ]:
print(x.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
mean=x["Calories"].mean()
x["Calories"].fillna(mean,inplace=True)
print(x.to_string())
print(mean)

     Duration  Pulse  Maxpulse     Calories
0          60    110       130   409.100000
1          60    117       145   479.000000
2          60    103       135   340.000000
3          45    109       175   282.400000
4          45    117       148   406.000000
5          60    102       127   300.000000
6          60    110       136   374.000000
7          45    104       134   253.300000
8          30    109       133   195.100000
9          60     98       124   269.000000
10         60    103       147   329.300000
11         60    100       120   250.700000
12         60    106       128   345.300000
13         60    104       132   379.300000
14         60     98       123   275.000000
15         60     98       120   215.200000
16         60    100       120   300.000000
17         45     90       112   375.790244
18         60    103       123   323.000000
19         45     97       125   243.000000
20         60    108       131   364.200000
21         45    100       119   282.000000
22         60    130       101   300.000000
23         45    105       132   246.000000
24         60    102       126   334.500000
25         60    100       120   250.000000
26         60     92       118   241.000000
27         60    103       132   375.790244
28         60    100       132   280.000000
29         60    102       129   380.300000
30         60     92       115   243.000000
31         45     90       112   180.100000
32         60    101       124   299.000000
33         60     93       113   223.000000
34         60    107       136   361.000000
35         60    114       140   415.000000
36         60    102       127   300.000000
37         60    100       120   300.000000
38         60    100       120   300.000000
39         45    104       129   266.000000
40         45     90       112   180.100000
41         60     98       126   286.000000
42         60    100       122   329.400000
43         60    111       138   400.000000
44         60    111       131   397.000000
45         60     99       119   273.000000
46         60    109       153   387.600000
47         45    111       136   300.000000
48         45    108       129   298.000000
49         60    111       139   397.600000
50         60    107       136   380.200000
51         80    123       146   643.100000
52         60    106       130   263.000000
53         60    118       151   486.000000
54         30    136       175   238.000000
55         60    121       146   450.700000
56         60    118       121   413.000000
57         45    115       144   305.000000
58         20    153       172   226.400000
59         45    123       152   321.000000
60        210    108       160  1376.000000
61        160    110       137  1034.400000
62        160    109       135   853.000000
63         45    118       141   341.000000
64         20    110       130   131.400000
65        180     90       130   800.400000
66        150    105       135   873.400000
67        150    107       130   816.000000
68         20    106       136   110.400000
69        300    108       143  1500.200000
70        150     97       129  1115.000000
71         60    109       153   387.600000
72         90    100       127   700.000000
73        150     97       127   953.200000
74         45    114       146   304.000000
75         90     98       125   563.200000
76         45    105       134   251.000000
77         45    110       141   300.000000
78        120    100       130   500.400000
79        270    100       131  1729.000000
80         30    159       182   319.200000
81         45    149       169   344.000000
82         30    103       139   151.100000
83        120    100       130   500.000000
84         45    100       120   225.300000
85         30    151       170   300.000000
86         45    102       136   234.000000
87        120    100       157  1000.100000
88         45    129       103   242.000000
89         20     83       107    50.300000
90        180    101       127   600.100000
91         45    107       137   375.790244
92         30     90       107   105.300000
93         15     80       100    50.500000
94         20    150       171   127.400000
95         20    151       168   229.400000
96         30     95       128   128.200000
97         25    152       168   244.200000
98         30    109       131   188.200000
99         90     93       124   604.100000
100        20     95       112    77.700000
101        90     90       110   500.000000
102        90     90       100   500.000000
103        90     90       100   500.400000
104        30     92       108    92.700000
105        30     93       128   124.000000
106       180     90       120   800.300000
107        30     90       120    86.200000
108        90     90       120   500.300000
109       210    137       184  1860.400000
110        60    102       124   325.200000
111        45    107       124   275.000000
112        15    124       139   124.200000
113        45    100       120   225.300000
114        60    108       131   367.600000
115        60    108       151   351.700000
116        60    116       141   443.000000
117        60     97       122   277.400000
118        60    105       125   375.790244
119        60    103       124   332.700000
120        30    112       137   193.900000
121        45    100       120   100.700000
122        60    119       169   336.700000
123        60    107       127   344.900000
124        60    111       151   368.500000
125        60     98       122   271.000000
126        60     97       124   275.300000
127        60    109       127   382.000000
128        90     99       125   466.400000
129        60    114       151   384.000000
130        60    104       134   342.500000
131        60    107       138   357.500000
132        60    103       133   335.000000
133        60    106       132   327.500000
134        60    103       136   339.000000
135        20    136       156   189.000000
136        45    117       143   317.700000
137        45    115       137   318.000000
138        45    113       138   308.000000
139        20    141       162   222.400000
140        60    108       135   390.000000
141        60     97       127   375.790244
142        45    100       120   250.400000
143        45    122       149   335.400000
144        60    136       170   470.200000
145        45    106       126   270.800000
146        60    107       136   400.000000
147        60    112       146   361.900000
148        30    103       127   185.000000
149        60    110       150   409.400000
150        60    106       134   343.000000
151        60    109       129   353.200000
152        60    109       138   374.000000
153        30    150       167   275.800000
154        60    105       128   328.000000
155        60    111       151   368.500000
156        60     97       131   270.400000
157        60    100       120   270.400000
158        60    114       150   382.800000
159        30     80       120   240.900000
160        30     85       120   250.400000
161        45     90       130   260.400000
162        45     95       130   270.000000
163        45    100       140   280.900000
164        60    105       140   290.800000
165        60    110       145   300.000000
166        60    115       145   310.200000
167        75    120       150   320.400000
168        75    125       150   330.400000
375.79024390243904

## replace null values in company info using Mean,Median,Mode

In [ ]:
import pandas as pd

In [ ]:
x=pd.read_csv("/content/company info - Sheet1 (2).csv")
print(x.to_string())

    emp_id      emp_name             job role    salary  experience
0   1001.0         edwin              teacher   30000.0         2.0
1   1002.0         david              trainer       NaN         3.0
2   1003.0        shifan               farmer   23000.0         NaN
3   1004.0         insaf              plumber   35000.0         2.0
4   1005.0           NaN               barber       NaN         1.0
5   1006.0        adarsh               driver       NaN         5.0
6   1007.0         madhu               helper   60000.0         3.0
7      NaN           NaN              cleaner   70000.0         NaN
8   1009.0          ajin                 cook   80000.0         4.0
9   1010.0          lijo            developer   67000.0         2.0
10  1011.0          sijo           accountant   45000.0         3.0
11  1012.0          biju              manager   68400.0         1.0
12  1013.0         baiju             chairman   87850.0         3.0
13  1014.0         shiju               police   46750.0         4.0
14  1015.0           abi                   hr   90000.0         3.0
15  1016.0        abinav            marketing   75000.0         3.0
16  1017.0        salman                  ceo       NaN         2.0
17  1018.0         sanju               doctor   50000.0         4.0
18  1019.0           NaN             engineer   80000.0         1.0
19  1020.0          zain                nurse       NaN         3.0
20  1021.0          ebin             catering  355000.0         5.0
21  1022.0           NaN            carpender   54600.0         2.0
22  1023.0        rishad              teacher  454600.0         4.0
23  1024.0          jijo             security   47500.0         4.0
24  1025.0         aslam            condector    9000.0         2.0
25  1026.0       sugunan               waiter    5000.0         2.0
26     NaN           sam               helper    6000.0         NaN
27  1028.0          alwi               pailet       NaN         5.0
28  1029.0           NaN             engineer   67000.0         6.0
29  1030.0         binoy                  NaN   76900.0         2.0
30     NaN           NaN    marketing manager   90000.0         NaN
31  1032.0         mellu             mechanic       NaN         1.0
32  1033.0         jeeva                  NaN   30000.0         4.0
33  1034.0          suni                shuff   70500.0         2.0
34  1035.0           NaN              fireman       NaN         5.0
35     NaN           ajo       forest officer  100000.0         2.0
36  1037.0          lalu        animal doctor       NaN         2.0
37  1038.0          manu                  NaN   83830.0         1.0
38  1039.0     emmanuvel              trainer    5750.0         1.0
39     NaN         saaka               exerse   75870.0         4.0
40  1041.0           NaN               driver       NaN         3.0
41  1042.0         messi         business man       NaN         5.0
42  1043.0           abu             mechanic    5000.0         3.0
43     NaN          joel  digital engineering    7000.0         2.0
44  1045.0          noha                   ca  577700.0         4.0
45  1046.0           NaN                staff   50000.0         1.0
46  1047.0         sunny              cashier   90000.0        11.0
47  1048.0          miya            collector  849900.0        10.0
48  1049.0  danidaniyels             minister   90900.0         8.0
49  1050.0       thulasi             cleaning   15000.0         4.0

In [ ]:
mean=x["experience"].mean()
x["experience"].fillna(mean,inplace=True)
print(mean)

3.347826086956522

In [ ]:
print(x.to_string())

    emp_id      emp_name             job role    salary  experience
0   1001.0         edwin              teacher   30000.0    2.000000
1   1002.0         david              trainer       NaN    3.000000
2   1003.0        shifan               farmer   23000.0    3.347826
3   1004.0         insaf              plumber   35000.0    2.000000
4   1005.0           NaN               barber       NaN    1.000000
5   1006.0        adarsh               driver       NaN    5.000000
6   1007.0         madhu               helper   60000.0    3.000000
7      NaN           NaN              cleaner   70000.0    3.347826
8   1009.0          ajin                 cook   80000.0    4.000000
9   1010.0          lijo            developer   67000.0    2.000000
10  1011.0          sijo           accountant   45000.0    3.000000
11  1012.0          biju              manager   68400.0    1.000000
12  1013.0         baiju             chairman   87850.0    3.000000
13  1014.0         shiju               police   46750.0    4.000000
14  1015.0           abi                   hr   90000.0    3.000000
15  1016.0        abinav            marketing   75000.0    3.000000
16  1017.0        salman                  ceo       NaN    2.000000
17  1018.0         sanju               doctor   50000.0    4.000000
18  1019.0           NaN             engineer   80000.0    1.000000
19  1020.0          zain                nurse       NaN    3.000000
20  1021.0          ebin             catering  355000.0    5.000000
21  1022.0           NaN            carpender   54600.0    2.000000
22  1023.0        rishad              teacher  454600.0    4.000000
23  1024.0          jijo             security   47500.0    4.000000
24  1025.0         aslam            condector    9000.0    2.000000
25  1026.0       sugunan               waiter    5000.0    2.000000
26     NaN           sam               helper    6000.0    3.347826
27  1028.0          alwi               pailet       NaN    5.000000
28  1029.0           NaN             engineer   67000.0    6.000000
29  1030.0         binoy                  NaN   76900.0    2.000000
30     NaN           NaN    marketing manager   90000.0    3.347826
31  1032.0         mellu             mechanic       NaN    1.000000
32  1033.0         jeeva                  NaN   30000.0    4.000000
33  1034.0          suni                shuff   70500.0    2.000000
34  1035.0           NaN              fireman       NaN    5.000000
35     NaN           ajo       forest officer  100000.0    2.000000
36  1037.0          lalu        animal doctor       NaN    2.000000
37  1038.0          manu                  NaN   83830.0    1.000000
38  1039.0     emmanuvel              trainer    5750.0    1.000000
39     NaN         saaka               exerse   75870.0    4.000000
40  1041.0           NaN               driver       NaN    3.000000
41  1042.0         messi         business man       NaN    5.000000
42  1043.0           abu             mechanic    5000.0    3.000000
43     NaN          joel  digital engineering    7000.0    2.000000
44  1045.0          noha                   ca  577700.0    4.000000
45  1046.0           NaN                staff   50000.0    1.000000
46  1047.0         sunny              cashier   90000.0   11.000000
47  1048.0          miya            collector  849900.0   10.000000
48  1049.0  danidaniyels             minister   90900.0    8.000000
49  1050.0       thulasi             cleaning   15000.0    4.000000

In [ ]:
median=x["salary"].median()
print(median)

67000.0

In [ ]:
x["salary"].fillna(median,inplace=True)
print(x.to_string())

    emp_id      emp_name             job role    salary  experience
0   1001.0         edwin              teacher   30000.0    2.000000
1   1002.0         david              trainer   67000.0    3.000000
2   1003.0        shifan               farmer   23000.0    3.347826
3   1004.0         insaf              plumber   35000.0    2.000000
4   1005.0           NaN               barber   67000.0    1.000000
5   1006.0        adarsh               driver   67000.0    5.000000
6   1007.0         madhu               helper   60000.0    3.000000
7      NaN           NaN              cleaner   70000.0    3.347826
8   1009.0          ajin                 cook   80000.0    4.000000
9   1010.0          lijo            developer   67000.0    2.000000
10  1011.0          sijo           accountant   45000.0    3.000000
11  1012.0          biju              manager   68400.0    1.000000
12  1013.0         baiju             chairman   87850.0    3.000000
13  1014.0         shiju               police   46750.0    4.000000
14  1015.0           abi                   hr   90000.0    3.000000
15  1016.0        abinav            marketing   75000.0    3.000000
16  1017.0        salman                  ceo   67000.0    2.000000
17  1018.0         sanju               doctor   50000.0    4.000000
18  1019.0           NaN             engineer   80000.0    1.000000
19  1020.0          zain                nurse   67000.0    3.000000
20  1021.0          ebin             catering  355000.0    5.000000
21  1022.0           NaN            carpender   54600.0    2.000000
22  1023.0        rishad              teacher  454600.0    4.000000
23  1024.0          jijo             security   47500.0    4.000000
24  1025.0         aslam            condector    9000.0    2.000000
25  1026.0       sugunan               waiter    5000.0    2.000000
26     NaN           sam               helper    6000.0    3.347826
27  1028.0          alwi               pailet   67000.0    5.000000
28  1029.0           NaN             engineer   67000.0    6.000000
29  1030.0         binoy                  NaN   76900.0    2.000000
30     NaN           NaN    marketing manager   90000.0    3.347826
31  1032.0         mellu             mechanic   67000.0    1.000000
32  1033.0         jeeva                  NaN   30000.0    4.000000
33  1034.0          suni                shuff   70500.0    2.000000
34  1035.0           NaN              fireman   67000.0    5.000000
35     NaN           ajo       forest officer  100000.0    2.000000
36  1037.0          lalu        animal doctor   67000.0    2.000000
37  1038.0          manu                  NaN   83830.0    1.000000
38  1039.0     emmanuvel              trainer    5750.0    1.000000
39     NaN         saaka               exerse   75870.0    4.000000
40  1041.0           NaN               driver   67000.0    3.000000
41  1042.0         messi         business man   67000.0    5.000000
42  1043.0           abu             mechanic    5000.0    3.000000
43     NaN          joel  digital engineering    7000.0    2.000000
44  1045.0          noha                   ca  577700.0    4.000000
45  1046.0           NaN                staff   50000.0    1.000000
46  1047.0         sunny              cashier   90000.0   11.000000
47  1048.0          miya            collector  849900.0   10.000000
48  1049.0  danidaniyels             minister   90900.0    8.000000
49  1050.0       thulasi             cleaning   15000.0    4.000000

In [ ]:
mode=x["emp_id"].mode()[0]
print(mode)

1001.0

In [ ]:
x["emp_id"].fillna(mode,inplace=True)
print(x.to_string())

    emp_id      emp_name             job role    salary  experience
0   1001.0         edwin              teacher   30000.0    2.000000
1   1002.0         david              trainer   67000.0    3.000000
2   1003.0        shifan               farmer   23000.0    3.347826
3   1004.0         insaf              plumber   35000.0    2.000000
4   1005.0           NaN               barber   67000.0    1.000000
5   1006.0        adarsh               driver   67000.0    5.000000
6   1007.0         madhu               helper   60000.0    3.000000
7   1001.0           NaN              cleaner   70000.0    3.347826
8   1009.0          ajin                 cook   80000.0    4.000000
9   1010.0          lijo            developer   67000.0    2.000000
10  1011.0          sijo           accountant   45000.0    3.000000
11  1012.0          biju              manager   68400.0    1.000000
12  1013.0         baiju             chairman   87850.0    3.000000
13  1014.0         shiju               police   46750.0    4.000000
14  1015.0           abi                   hr   90000.0    3.000000
15  1016.0        abinav            marketing   75000.0    3.000000
16  1017.0        salman                  ceo   67000.0    2.000000
17  1018.0         sanju               doctor   50000.0    4.000000
18  1019.0           NaN             engineer   80000.0    1.000000
19  1020.0          zain                nurse   67000.0    3.000000
20  1021.0          ebin             catering  355000.0    5.000000
21  1022.0           NaN            carpender   54600.0    2.000000
22  1023.0        rishad              teacher  454600.0    4.000000
23  1024.0          jijo             security   47500.0    4.000000
24  1025.0         aslam            condector    9000.0    2.000000
25  1026.0       sugunan               waiter    5000.0    2.000000
26  1001.0           sam               helper    6000.0    3.347826
27  1028.0          alwi               pailet   67000.0    5.000000
28  1029.0           NaN             engineer   67000.0    6.000000
29  1030.0         binoy                  NaN   76900.0    2.000000
30  1001.0           NaN    marketing manager   90000.0    3.347826
31  1032.0         mellu             mechanic   67000.0    1.000000
32  1033.0         jeeva                  NaN   30000.0    4.000000
33  1034.0          suni                shuff   70500.0    2.000000
34  1035.0           NaN              fireman   67000.0    5.000000
35  1001.0           ajo       forest officer  100000.0    2.000000
36  1037.0          lalu        animal doctor   67000.0    2.000000
37  1038.0          manu                  NaN   83830.0    1.000000
38  1039.0     emmanuvel              trainer    5750.0    1.000000
39  1001.0         saaka               exerse   75870.0    4.000000
40  1041.0           NaN               driver   67000.0    3.000000
41  1042.0         messi         business man   67000.0    5.000000
42  1043.0           abu             mechanic    5000.0    3.000000
43  1001.0          joel  digital engineering    7000.0    2.000000
44  1045.0          noha                   ca  577700.0    4.000000
45  1046.0           NaN                staff   50000.0    1.000000
46  1047.0         sunny              cashier   90000.0   11.000000
47  1048.0          miya            collector  849900.0   10.000000
48  1049.0  danidaniyels             minister   90900.0    8.000000
49  1050.0       thulasi             cleaning   15000.0    4.000000

# FiLLNA WITH ANOTHR DATASET

In [ ]:
import pandas as pd

In [ ]:
df2=pd.read_csv("/content/company_data_with_nulls.csv")

In [ ]:
print(df2.to_string())

     Column_1  Column_2  Column_3  Column_4  Column_5  Column_6
0       688.0     764.0     829.0     669.0       NaN     995.0
1       883.0       NaN       NaN     317.0     906.0       NaN
2         NaN     519.0     533.0       NaN     362.0     220.0
3       223.0       NaN     792.0       NaN     329.0     379.0
4       780.0       5.0     145.0     146.0     109.0     828.0
5         NaN     919.0     306.0     149.0     478.0       NaN
6       643.0     981.0     705.0       NaN     546.0     584.0
7       315.0     408.0       NaN       NaN       NaN     366.0
8       165.0     223.0     555.0     190.0     358.0     748.0
9         NaN     522.0     971.0     337.0     599.0     669.0
10      541.0       NaN       NaN     771.0       NaN     437.0
11        NaN     422.0     164.0     684.0     164.0       NaN
12       48.0     664.0    1000.0     444.0       NaN     793.0
13      804.0     983.0       NaN       NaN       NaN       NaN
14      656.0       NaN      34.0      74.0     776.0       NaN
15        NaN     392.0     197.0       NaN     829.0     776.0
16        NaN       NaN     396.0     943.0     363.0     237.0
17        NaN       NaN     341.0     691.0       NaN     310.0
18      664.0     283.0       NaN      34.0     808.0     143.0
19      691.0     529.0      17.0       NaN     690.0     606.0
20        NaN       NaN       NaN     866.0     673.0       NaN
21      965.0     787.0       NaN     690.0       NaN       NaN
22      476.0     563.0     678.0     633.0     369.0     883.0
23      951.0       NaN     115.0     750.0       NaN     788.0
24      810.0     776.0      36.0     605.0     567.0     375.0
25      874.0     754.0      56.0       NaN       NaN       NaN
26      675.0      77.0       NaN     158.0       NaN     927.0
27        NaN     158.0     384.0     729.0     565.0       NaN
28      413.0       NaN     923.0     291.0       NaN     800.0
29        NaN     225.0     283.0       NaN     913.0     168.0
30        NaN       NaN       NaN     920.0     485.0     911.0
31        NaN       NaN     738.0       NaN      43.0     496.0
32        NaN     861.0     831.0       NaN      87.0     136.0
33      403.0       NaN       NaN       NaN     553.0       NaN
34      476.0     917.0     622.0     885.0      31.0     744.0
35       50.0       NaN     438.0     264.0       NaN       NaN
36      466.0       NaN      33.0       NaN       NaN       NaN
37      962.0       NaN     548.0       NaN     267.0     864.0
38      456.0     202.0     803.0     828.0       NaN       NaN
39        NaN       NaN     863.0     997.0       NaN     279.0
40        NaN       NaN     551.0     453.0     480.0     462.0
41        NaN      32.0     356.0     937.0       NaN     870.0
42      353.0     516.0      16.0     708.0     654.0     838.0
43        NaN       NaN     446.0     835.0       NaN     880.0
44        NaN     533.0     256.0     331.0     451.0       NaN
45      244.0       NaN      91.0       NaN     204.0     987.0
46        NaN     940.0       NaN      79.0      98.0     735.0
47      727.0     537.0     756.0       4.0     924.0     749.0
48       45.0       NaN       NaN     385.0     530.0     800.0
49      485.0     687.0     119.0     796.0       NaN     216.0
50      651.0     442.0       NaN     227.0     311.0     424.0
51        NaN     474.0     965.0     116.0     426.0     208.0
52      155.0     100.0     397.0     480.0     387.0       NaN
53        NaN       NaN     127.0     198.0     122.0       NaN
54      844.0     213.0     124.0     919.0       NaN     595.0
55      820.0       NaN       NaN      70.0     318.0     268.0
56        NaN     244.0       NaN     403.0     624.0     373.0
57        NaN     767.0     162.0       NaN      46.0     770.0
58      567.0     998.0     196.0       NaN      86.0     799.0
59      452.0       NaN     162.0     826.0       NaN       NaN
60      395.0       NaN     506.0     103.0      36.0     149.0
61      883.0       NaN     166.0     942.0     965.0     903.0
62      603.0       NaN     194.0       NaN       NaN     813.0
63      487.0       NaN     277.0     558.0     602.0       NaN
64      838.0     911.0     131.0     823.0     398.0     101.0
65        NaN     493.0     250.0       NaN     306.0       NaN
66      256.0     785.0     556.0       NaN     929.0     816.0
67      387.0       NaN       NaN     439.0     839.0       NaN
68      241.0     537.0     952.0     432.0     566.0       NaN
69        NaN     951.0       NaN       NaN     565.0     847.0
70      949.0     980.0     310.0     804.0       NaN     765.0
71      777.0     519.0     295.0      19.0     320.0       NaN
72        NaN     928.0       NaN     303.0     636.0     832.0
73      459.0     507.0     363.0     688.0     736.0     835.0
74      314.0     676.0       NaN     199.0     276.0       NaN
75      493.0       NaN     868.0     893.0       NaN      47.0
76      106.0       NaN       NaN     988.0       NaN       NaN
77       50.0       NaN     800.0       NaN     291.0     104.0
78       53.0       NaN     328.0       NaN       NaN     383.0
79      965.0     718.0     652.0       NaN     545.0     180.0
80      220.0       NaN     903.0       NaN       NaN       NaN
81        NaN     546.0      39.0       NaN       NaN     839.0
82      433.0     424.0      53.0     531.0     277.0     235.0
83        NaN     198.0       NaN     995.0      65.0       NaN
84      233.0      37.0     197.0     943.0     373.0      18.0
85      701.0     755.0     997.0       NaN     450.0       NaN
86      721.0     330.0     180.0     384.0     521.0     485.0
87      107.0     194.0      47.0      15.0       NaN     873.0
88        3.0     830.0      88.0     455.0     364.0     667.0
89       15.0     353.0       NaN     826.0       NaN     372.0
90      681.0     129.0       NaN       NaN     471.0     116.0
91      742.0     427.0      41.0       NaN       NaN     524.0
92       11.0       8.0     167.0     830.0     149.0     619.0
93        NaN     703.0       NaN     741.0     710.0     836.0
94      622.0     356.0       NaN     831.0       NaN      50.0
95      238.0       NaN     805.0      99.0       NaN     994.0
96      998.0       NaN       NaN       NaN     815.0     215.0
97      693.0     152.0       NaN      83.0       NaN     877.0
98      782.0      24.0      72.0     524.0     642.0     281.0
99      611.0     307.0     449.0       NaN       NaN     146.0
100       NaN     278.0     558.0     934.0     600.0     210.0
101     837.0      63.0     920.0       NaN     236.0     421.0
102       NaN     482.0       NaN     130.0       NaN     783.0
103     321.0       NaN     631.0     216.0     351.0     292.0
104       NaN     168.0       NaN       NaN     240.0      72.0
105     956.0     242.0     665.0     229.0     531.0       NaN
106       NaN       NaN       NaN       NaN       NaN       NaN
107      11.0     309.0     533.0      73.0     188.0     226.0
108       NaN       NaN     194.0       NaN       NaN     306.0
109     644.0     572.0     915.0     338.0       NaN       NaN
110     485.0       NaN     175.0     727.0     692.0     382.0
111       NaN     193.0     298.0       NaN       NaN       8.0
112       NaN     120.0     422.0     970.0     389.0     192.0
113     608.0     118.0       NaN     791.0     264.0       NaN
114      48.0     522.0     801.0     231.0     286.0     164.0
115     917.0     838.0       NaN     135.0     667.0     300.0
116     563.0     695.0     829.0       NaN       NaN       NaN
117     171.0     854.0       NaN     962.0     788.0       NaN
118     207.0       NaN      73.0     654.0       NaN     904.0
119       NaN       NaN       NaN     492.0     319.0     209.0
120     829.0     503.0      78.0       NaN       NaN     542.0
121     601.0     651.0     999.0     416.0       NaN     824.0
122     122.0     445.0     360.0      80.0     877.0     811.0
123     724.0     865.0     223.0     834.0     931.0     669.0
124     180.0     151.0     212.0       NaN       NaN     648.0
125     164.0     942.0     772.0       NaN     688.0       NaN
126       NaN     746.0     814.0       NaN     256.0     779.0
127     457.0     871.0     469.0      64.0       NaN     305.0
128     834.0     768.0     767.0     105.0     703.0       NaN
129       NaN     504.0     195.0       NaN     999.0      84.0
130     296.0     909.0       NaN       NaN     615.0     779.0
131     299.0       NaN      25.0      36.0       NaN     822.0
132     770.0     994.0     218.0     367.0      31.0       NaN
133     360.0     299.0     878.0     561.0     978.0       NaN
134     469.0       NaN     852.0     380.0       NaN     551.0
135     964.0     879.0     620.0     591.0     387.0       NaN
136     813.0       NaN     138.0     564.0     660.0       NaN
137     170.0     782.0     772.0       9.0       NaN     819.0
138     255.0       NaN      54.0     759.0       NaN     829.0
139      62.0     650.0     690.0     875.0     498.0       NaN
140     368.0     156.0      40.0     684.0       NaN       NaN
141     197.0       NaN     745.0       NaN       NaN       NaN
142     282.0     911.0     980.0     425.0       NaN     448.0
143     332.0     440.0     982.0     214.0       NaN     350.0
144     316.0       NaN     195.0     540.0       NaN      56.0
145       NaN     150.0     190.0       NaN       NaN       NaN
146     462.0     507.0     681.0       NaN    1000.0     319.0
147     752.0     873.0     559.0     850.0     864.0     708.0
148       NaN       NaN       NaN     524.0     366.0       NaN
149     370.0     881.0       NaN     230.0     418.0     792.0
150     216.0       NaN     925.0     239.0     526.0     875.0
151     333.0     310.0     233.0       NaN     235.0     392.0
152       NaN     849.0     888.0     149.0       NaN     816.0
153      60.0     777.0     565.0       NaN       NaN     290.0
154     425.0     138.0       NaN     378.0       NaN     852.0
155       NaN     148.0       NaN     730.0      76.0       NaN
156      30.0     710.0     238.0     340.0     300.0     218.0
157       NaN     975.0     723.0       NaN       NaN       NaN
158     361.0     722.0     722.0     298.0     143.0     247.0
159       NaN     621.0       NaN     920.0       NaN       NaN
160     698.0     542.0     889.0       NaN     607.0     276.0
161       NaN     620.0     753.0     926.0     222.0      14.0
162     512.0     555.0     483.0     504.0     239.0       NaN
163       NaN     563.0     646.0     692.0       NaN     761.0
164     200.0     405.0     336.0       NaN       NaN     843.0
165     364.0     310.0     118.0     312.0     561.0     656.0
166       NaN     201.0     523.0     660.0     748.0       NaN
167     305.0     265.0       NaN     718.0     318.0       NaN
168     959.0       NaN     235.0     649.0     909.0     688.0
169     893.0       NaN     928.0     924.0     840.0      54.0
170       NaN     968.0       NaN     795.0       NaN       NaN
171     300.0       NaN     161.0     158.0     650.0       NaN
172      96.0       NaN     739.0      78.0     217.0       NaN
173     196.0     719.0      51.0     607.0       NaN     724.0
174     610.0      39.0       NaN     711.0     406.0     632.0
175     460.0       NaN       NaN     856.0     887.0     438.0
176     849.0     584.0       NaN       NaN       NaN     989.0
177     312.0     129.0     658.0     424.0     325.0       4.0
178       NaN       NaN       NaN     597.0       NaN     105.0
179       NaN     368.0     938.0     572.0     360.0     543.0
180       NaN     533.0     545.0     635.0       NaN     905.0
181     347.0      85.0       NaN     227.0     967.0     980.0
182      78.0     139.0     814.0       NaN     982.0       NaN
183     638.0     831.0       NaN     443.0       NaN      76.0
184     621.0       NaN     766.0       NaN     760.0     500.0
185     450.0       NaN     157.0     348.0      87.0     977.0
186     375.0       NaN       NaN     817.0       NaN     879.0
187     749.0     588.0      35.0       NaN       NaN       NaN
188       NaN       NaN       NaN       NaN       NaN       NaN
189     972.0     800.0     663.0       NaN       NaN       NaN
190     344.0       NaN     821.0       NaN     957.0       NaN
191     427.0     672.0       NaN     154.0     638.0       NaN
192     344.0       NaN       NaN     937.0     432.0     472.0
193       NaN       NaN     818.0     411.0       NaN     655.0
194     600.0     891.0     700.0       NaN     198.0     445.0
195     258.0       NaN     441.0     612.0       NaN       NaN
196     807.0     159.0     173.0       NaN     734.0     786.0
197     766.0     493.0     787.0     647.0       NaN     391.0
198     236.0     110.0       NaN     115.0       NaN     855.0
199     872.0       NaN      89.0     715.0     814.0     436.0
200     704.0     636.0     226.0     305.0     134.0     537.0
201     711.0      50.0     801.0      75.0     644.0      68.0
202     302.0     295.0       NaN     343.0     130.0       NaN
203       NaN     762.0       NaN     760.0     387.0     510.0
204     958.0     418.0     722.0     616.0     331.0       NaN
205     112.0     767.0     958.0       NaN       1.0     337.0
206     145.0     718.0     316.0       NaN       NaN     629.0
207     607.0       NaN     340.0     577.0     905.0       NaN
208       NaN     866.0     875.0     429.0      10.0       NaN
209     651.0     623.0     591.0      78.0     495.0     512.0
210     869.0       NaN     657.0     366.0     852.0     601.0
211     931.0       NaN     867.0      61.0     175.0     168.0
212     197.0     879.0     970.0     309.0      98.0     966.0
213       NaN     275.0       NaN     779.0     197.0     987.0
214       NaN       NaN      49.0     367.0     582.0     574.0
215     905.0     733.0      46.0       NaN       NaN     809.0
216     779.0     424.0     662.0     196.0       NaN     399.0
217     292.0     126.0     982.0     989.0     938.0     434.0
218     704.0     102.0     588.0     213.0     789.0     114.0
219     649.0     855.0     358.0       NaN     325.0       NaN
220     374.0      38.0     839.0     471.0      88.0     786.0
221     584.0      77.0     443.0     837.0     345.0     111.0
222       4.0     795.0      56.0     235.0      25.0       NaN
223       NaN     114.0      11.0     594.0       NaN       NaN
224     302.0     211.0     225.0     805.0     587.0       6.0
225     863.0      10.0     477.0     442.0     113.0     396.0
226     366.0     771.0     204.0       NaN      57.0     653.0
227     782.0     262.0      21.0     595.0       NaN     610.0
228     247.0     716.0       NaN     888.0       NaN     320.0
229     502.0     237.0     183.0     928.0     242.0     981.0
230     424.0     814.0     175.0     395.0     361.0     325.0
231     244.0       NaN     849.0     714.0     694.0     214.0
232     901.0       NaN       NaN      41.0     543.0       NaN
233     945.0       NaN       NaN       NaN       NaN      97.0
234     726.0     412.0     342.0     983.0     462.0     540.0
235     157.0     597.0     971.0     878.0     356.0     213.0
236     283.0     274.0      94.0       9.0       NaN     105.0
237       NaN     424.0      40.0     901.0     831.0      95.0
238     840.0     686.0     311.0       NaN       NaN       NaN
239       NaN       NaN     359.0       NaN      47.0     767.0
240      95.0     618.0       NaN       NaN     369.0     786.0
241       NaN     919.0     257.0     314.0     473.0     909.0
242     205.0     467.0     380.0       NaN      37.0       1.0
243     881.0     767.0     466.0       NaN       NaN       NaN
244       NaN       NaN       NaN     806.0     331.0       NaN
245       NaN      56.0       NaN     680.0       NaN     582.0
246     954.0     604.0     359.0       NaN       NaN      11.0
247     211.0     782.0      38.0       NaN     474.0       NaN
248       NaN       NaN       1.0       NaN       NaN     958.0
249     383.0     916.0       NaN     649.0       NaN     922.0
250      34.0     598.0     283.0       NaN     948.0     947.0
251     838.0     237.0       NaN     929.0       NaN     306.0
252     370.0     299.0       NaN       NaN     838.0       NaN
253     201.0     471.0     194.0     706.0     803.0     838.0
254      25.0     197.0     527.0       NaN     707.0     681.0
255     250.0     309.0     184.0     869.0     831.0     700.0
256     646.0     358.0     280.0     191.0     186.0     591.0
257       NaN       NaN     173.0     540.0     991.0       NaN
258     513.0       NaN     460.0       NaN       NaN     373.0
259       NaN     469.0     472.0       NaN       NaN       NaN
260     624.0       NaN     382.0       NaN       NaN      61.0
261       NaN      80.0     194.0     947.0      10.0     897.0
262     207.0      10.0     988.0     359.0     106.0     905.0
263     861.0     514.0      62.0     283.0       NaN     715.0
264       NaN     865.0       NaN       NaN       NaN     751.0
265     598.0     652.0       NaN     130.0     537.0       NaN
266      93.0     861.0     847.0     487.0      51.0     930.0
267     523.0     822.0       NaN     178.0       NaN     541.0
268     558.0       NaN       NaN     128.0     109.0       NaN
269     897.0     477.0     909.0       NaN     417.0     540.0
270     790.0       NaN     342.0     855.0       NaN     147.0
271     154.0       NaN      90.0     404.0     792.0     913.0
272       NaN     671.0       NaN       NaN     231.0       NaN
273       NaN       NaN     326.0     547.0       NaN     425.0
274     497.0     234.0       NaN       NaN       NaN       NaN
275     183.0       NaN       NaN     443.0     893.0     457.0
276     145.0       NaN     325.0       NaN       NaN     978.0
277     283.0     361.0     855.0       NaN     297.0     201.0
278     886.0     407.0     960.0     657.0       NaN     606.0
279       NaN     558.0     790.0     873.0     201.0     754.0
280       NaN      72.0     757.0     555.0     547.0     324.0
281       NaN     408.0     992.0     456.0     539.0       NaN
282     307.0     413.0       NaN     467.0     769.0     990.0
283     967.0       NaN     760.0       NaN     380.0     240.0
284       NaN     662.0       NaN     879.0     804.0     544.0
285       NaN     994.0     265.0     185.0       NaN      40.0
286     127.0     470.0       NaN       NaN       NaN     785.0
287     382.0     843.0     893.0     466.0     514.0     390.0
288       NaN      50.0       NaN       NaN       NaN     973.0
289     396.0     165.0     234.0       NaN     663.0     632.0
290     236.0       NaN       NaN     340.0       NaN     194.0
291     819.0       NaN       5.0     635.0     463.0     963.0
292     864.0     844.0       NaN     835.0     717.0      15.0
293     537.0       NaN     806.0     574.0       NaN     596.0
294     936.0      43.0     876.0       NaN       NaN       NaN
295     478.0       NaN     472.0       NaN     225.0     643.0
296     239.0     364.0     580.0     466.0     364.0     249.0
297     574.0     379.0       NaN     690.0     338.0     954.0
298     111.0     917.0     514.0     540.0     438.0       NaN
299     486.0       NaN     917.0       NaN       NaN       NaN
300     220.0       NaN     169.0      95.0     660.0      37.0
301     632.0     457.0     321.0     645.0     947.0     299.0
302     814.0      83.0     482.0       NaN       NaN       NaN
303     327.0     934.0     709.0     385.0     899.0       NaN
304     200.0      26.0       NaN     972.0     794.0     350.0
305     551.0     496.0     801.0     994.0     437.0       NaN
306       NaN     386.0     827.0       NaN     941.0       NaN
307     135.0       NaN     210.0       NaN     698.0     798.0
308     152.0      83.0     132.0     111.0     238.0       NaN
309       NaN       NaN       NaN     579.0     383.0       NaN
310     839.0     961.0      42.0     153.0       NaN     255.0

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column_1  285 non-null    float64
 1   Column_2  278 non-null    float64
 2   Column_3  291 non-null    float64
 3   Column_4  277 non-null    float64
 4   Column_5  266 non-null    float64
 5   Column_6  283 non-null    float64
dtypes: float64(6)
memory usage: 18.9 KB

In [ ]:
#mean=df2.mean()
#print(mean)

Column_1    489.361404
Column_2    502.881295
Column_3    472.323024
Column_4    503.444043
Column_5    489.646617
Column_6    508.173145
dtype: float64

In [ ]:
#df2.fillna(mean,inplace=True)
#print(df2.to_string())

In [ ]:
x=df2["Column_1"].mean()
print(x)
df2["Column_1"].fillna(mean,inplace=True)
print(df2["Column_1"].to_string())

489.36140350877196
0      688.000000
1      883.000000
2      489.361404
3      223.000000
4      780.000000
5      489.361404
6      643.000000
7      315.000000
8      165.000000
9      489.361404
10     541.000000
11     489.361404
12      48.000000
13     804.000000
14     656.000000
15     489.361404
16     489.361404
17     489.361404
18     664.000000
19     691.000000
20     489.361404
21     965.000000
22     476.000000
23     951.000000
24     810.000000
25     874.000000
26     675.000000
27     489.361404
28     413.000000
29     489.361404
30     489.361404
31     489.361404
32     489.361404
33     403.000000
34     476.000000
35      50.000000
36     466.000000
37     962.000000
38     456.000000
39     489.361404
40     489.361404
41     489.361404
42     353.000000
43     489.361404
44     489.361404
45     244.000000
46     489.361404
47     727.000000
48      45.000000
49     485.000000
50     651.000000
51     489.361404
52     155.000000
53     489.361404
54     844.000000
55     820.000000
56     489.361404
57     489.361404
58     567.000000
59     452.000000
60     395.000000
61     883.000000
62     603.000000
63     487.000000
64     838.000000
65     489.361404
66     256.000000
67     387.000000
68     241.000000
69     489.361404
70     949.000000
71     777.000000
72     489.361404
73     459.000000
74     314.000000
75     493.000000
76     106.000000
77      50.000000
78      53.000000
79     965.000000
80     220.000000
81     489.361404
82     433.000000
83     489.361404
84     233.000000
85     701.000000
86     721.000000
87     107.000000
88       3.000000
89      15.000000
90     681.000000
91     742.000000
92      11.000000
93     489.361404
94     622.000000
95     238.000000
96     998.000000
97     693.000000
98     782.000000
99     611.000000
100    489.361404
101    837.000000
102    489.361404
103    321.000000
104    489.361404
105    956.000000
106    489.361404
107     11.000000
108    489.361404
109    644.000000
110    485.000000
111    489.361404
112    489.361404
113    608.000000
114     48.000000
115    917.000000
116    563.000000
117    171.000000
118    207.000000
119    489.361404
120    829.000000
121    601.000000
122    122.000000
123    724.000000
124    180.000000
125    164.000000
126    489.361404
127    457.000000
128    834.000000
129    489.361404
130    296.000000
131    299.000000
132    770.000000
133    360.000000
134    469.000000
135    964.000000
136    813.000000
137    170.000000
138    255.000000
139     62.000000
140    368.000000
141    197.000000
142    282.000000
143    332.000000
144    316.000000
145    489.361404
146    462.000000
147    752.000000
148    489.361404
149    370.000000
150    216.000000
151    333.000000
152    489.361404
153     60.000000
154    425.000000
155    489.361404
156     30.000000
157    489.361404
158    361.000000
159    489.361404
160    698.000000
161    489.361404
162    512.000000
163    489.361404
164    200.000000
165    364.000000
166    489.361404
167    305.000000
168    959.000000
169    893.000000
170    489.361404
171    300.000000
172     96.000000
173    196.000000
174    610.000000
175    460.000000
176    849.000000
177    312.000000
178    489.361404
179    489.361404
180    489.361404
181    347.000000
182     78.000000
183    638.000000
184    621.000000
185    450.000000
186    375.000000
187    749.000000
188    489.361404
189    972.000000
190    344.000000
191    427.000000
192    344.000000
193    489.361404
194    600.000000
195    258.000000
196    807.000000
197    766.000000
198    236.000000
199    872.000000
200    704.000000
201    711.000000
202    302.000000
203    489.361404
204    958.000000
205    112.000000
206    145.000000
207    607.000000
208    489.361404
209    651.000000
210    869.000000
211    931.000000
212    197.000000
213    489.361404
214    489.361404
215    905.000000
216    779.000000
217    292.000000
218    704.000000
219    649.000000
220    374.000000
221    584.000000
222      4.000000
223    489.361404
224    302.000000
225    863.000000
226    366.000000
227    782.000000
228    247.000000
229    502.000000
230    424.000000
231    244.000000
232    901.000000
233    945.000000
234    726.000000
235    157.000000
236    283.000000
237    489.361404
238    840.000000
239    489.361404
240     95.000000
241    489.361404
242    205.000000
243    881.000000
244    489.361404
245    489.361404
246    954.000000
247    211.000000
248    489.361404
249    383.000000
250     34.000000
251    838.000000
252    370.000000
253    201.000000
254     25.000000
255    250.000000
256    646.000000
257    489.361404
258    513.000000
259    489.361404
260    624.000000
261    489.361404
262    207.000000
263    861.000000
264    489.361404
265    598.000000
266     93.000000
267    523.000000
268    558.000000
269    897.000000
270    790.000000
271    154.000000
272    489.361404
273    489.361404
274    497.000000
275    183.000000
276    145.000000
277    283.000000
278    886.000000
279    489.361404
280    489.361404
281    489.361404
282    307.000000
283    967.000000
284    489.361404
285    489.361404
286    127.000000
287    382.000000
288    489.361404
289    396.000000
290    236.000000
291    819.000000
292    864.000000
293    537.000000
294    936.000000
295    478.000000
296    239.000000
297    574.000000
298    111.000000
299    486.000000
300    220.000000
301    632.000000
302    814.000000
303    327.000000
304    200.000000
305    551.000000
306    489.361404
307    135.000000
308    152.000000
309    489.361404
310    839.000000
311     59.000000
312    489.361404
313    489.361404
314    124.000000
315    893.000000
316    377.000000
317    378.000000
318    368.000000
319    165.000000
320    489.361404
321     98.000000
322    489.361404
323    489.361404
324    616.000000
325    466.000000
326    324.000000
327    405.000000
328    946.000000
329    489.361404
330    603.000000
331    479.000000
332    489.361404
333    489.361404
334    519.000000
335    795.000000
336    659.000000
337    898.000000
338    489.361404
339    489.361404
340    102.000000
341    489.361404
342    489.361404
343    660.000000
344    489.361404
345    915.000000
346    533.000000
347    489.361404
348    489.361404
349    489.361404
350    246.000000
351      5.000000
352    219.000000
353    489.361404
354    211.000000
355    262.000000
356    988.000000
357    957.000000
358    704.000000
359    455.000000
360    489.361404
361    966.000000
362    357.000000
363    698.000000
364    216.000000
365    489.361404
366    280.000000
367    848.000000
368    850.000000
369    819.000000
370    489.361404
371    702.000000
372    489.361404
373    489.361404
374    150.000000
375    489.361404
376    516.000000
377    242.000000
378    847.000000
379    489.361404
380    489.361404
381    489.361404
382    489.361404
383    228.000000
384    489.361404
385    489.361404
386    489.361404
387    624.000000
388    182.000000
389    489.361404
390    489.361404
391    606.000000
392    489.361404
393    489.361404
394    489.361404
395     52.000000
396    762.000000
397    413.000000
398    489.361404
399    620.000000

In [ ]:
# replace colum_2 with median
med=df2["Column_2"].median()
print(med)
df2["Column_2"].fillna(med,inplace=True)
print(df2["Column_2"].to_string())

502.88129496402877
0      764.000000
1      502.881295
2      519.000000
3      502.881295
4        5.000000
5      919.000000
6      981.000000
7      408.000000
8      223.000000
9      522.000000
10     502.881295
11     422.000000
12     664.000000
13     983.000000
14     502.881295
15     392.000000
16     502.881295
17     502.881295
18     283.000000
19     529.000000
20     502.881295
21     787.000000
22     563.000000
23     502.881295
24     776.000000
25     754.000000
26      77.000000
27     158.000000
28     502.881295
29     225.000000
30     502.881295
31     502.881295
32     861.000000
33     502.881295
34     917.000000
35     502.881295
36     502.881295
37     502.881295
38     202.000000
39     502.881295
40     502.881295
41      32.000000
42     516.000000
43     502.881295
44     533.000000
45     502.881295
46     940.000000
47     537.000000
48     502.881295
49     687.000000
50     442.000000
51     474.000000
52     100.000000
53     502.881295
54     213.000000
55     502.881295
56     244.000000
57     767.000000
58     998.000000
59     502.881295
60     502.881295
61     502.881295
62     502.881295
63     502.881295
64     911.000000
65     493.000000
66     785.000000
67     502.881295
68     537.000000
69     951.000000
70     980.000000
71     519.000000
72     928.000000
73     507.000000
74     676.000000
75     502.881295
76     502.881295
77     502.881295
78     502.881295
79     718.000000
80     502.881295
81     546.000000
82     424.000000
83     198.000000
84      37.000000
85     755.000000
86     330.000000
87     194.000000
88     830.000000
89     353.000000
90     129.000000
91     427.000000
92       8.000000
93     703.000000
94     356.000000
95     502.881295
96     502.881295
97     152.000000
98      24.000000
99     307.000000
100    278.000000
101     63.000000
102    482.000000
103    502.881295
104    168.000000
105    242.000000
106    502.881295
107    309.000000
108    502.881295
109    572.000000
110    502.881295
111    193.000000
112    120.000000
113    118.000000
114    522.000000
115    838.000000
116    695.000000
117    854.000000
118    502.881295
119    502.881295
120    503.000000
121    651.000000
122    445.000000
123    865.000000
124    151.000000
125    942.000000
126    746.000000
127    871.000000
128    768.000000
129    504.000000
130    909.000000
131    502.881295
132    994.000000
133    299.000000
134    502.881295
135    879.000000
136    502.881295
137    782.000000
138    502.881295
139    650.000000
140    156.000000
141    502.881295
142    911.000000
143    440.000000
144    502.881295
145    150.000000
146    507.000000
147    873.000000
148    502.881295
149    881.000000
150    502.881295
151    310.000000
152    849.000000
153    777.000000
154    138.000000
155    148.000000
156    710.000000
157    975.000000
158    722.000000
159    621.000000
160    542.000000
161    620.000000
162    555.000000
163    563.000000
164    405.000000
165    310.000000
166    201.000000
167    265.000000
168    502.881295
169    502.881295
170    968.000000
171    502.881295
172    502.881295
173    719.000000
174     39.000000
175    502.881295
176    584.000000
177    129.000000
178    502.881295
179    368.000000
180    533.000000
181     85.000000
182    139.000000
183    831.000000
184    502.881295
185    502.881295
186    502.881295
187    588.000000
188    502.881295
189    800.000000
190    502.881295
191    672.000000
192    502.881295
193    502.881295
194    891.000000
195    502.881295
196    159.000000
197    493.000000
198    110.000000
199    502.881295
200    636.000000
201     50.000000
202    295.000000
203    762.000000
204    418.000000
205    767.000000
206    718.000000
207    502.881295
208    866.000000
209    623.000000
210    502.881295
211    502.881295
212    879.000000
213    275.000000
214    502.881295
215    733.000000
216    424.000000
217    126.000000
218    102.000000
219    855.000000
220     38.000000
221     77.000000
222    795.000000
223    114.000000
224    211.000000
225     10.000000
226    771.000000
227    262.000000
228    716.000000
229    237.000000
230    814.000000
231    502.881295
232    502.881295
233    502.881295
234    412.000000
235    597.000000
236    274.000000
237    424.000000
238    686.000000
239    502.881295
240    618.000000
241    919.000000
242    467.000000
243    767.000000
244    502.881295
245     56.000000
246    604.000000
247    782.000000
248    502.881295
249    916.000000
250    598.000000
251    237.000000
252    299.000000
253    471.000000
254    197.000000
255    309.000000
256    358.000000
257    502.881295
258    502.881295
259    469.000000
260    502.881295
261     80.000000
262     10.000000
263    514.000000
264    865.000000
265    652.000000
266    861.000000
267    822.000000
268    502.881295
269    477.000000
270    502.881295
271    502.881295
272    671.000000
273    502.881295
274    234.000000
275    502.881295
276    502.881295
277    361.000000
278    407.000000
279    558.000000
280     72.000000
281    408.000000
282    413.000000
283    502.881295
284    662.000000
285    994.000000
286    470.000000
287    843.000000
288     50.000000
289    165.000000
290    502.881295
291    502.881295
292    844.000000
293    502.881295
294     43.000000
295    502.881295
296    364.000000
297    379.000000
298    917.000000
299    502.881295
300    502.881295
301    457.000000
302     83.000000
303    934.000000
304     26.000000
305    496.000000
306    386.000000
307    502.881295
308     83.000000
309    502.881295
310    961.000000
311    778.000000
312    502.881295
313    502.881295
314    733.000000
315    846.000000
316    435.000000
317    673.000000
318    502.881295
319    502.881295
320    343.000000
321    751.000000
322    502.881295
323    886.000000
324    119.000000
325    551.000000
326    502.881295
327    502.881295
328    502.881295
329    669.000000
330    502.881295
331    823.000000
332    658.000000
333     26.000000
334    502.881295
335    436.000000
336    502.881295
337     46.000000
338     35.000000
339    151.000000
340    298.000000
341    410.000000
342    281.000000
343    502.881295
344    200.000000
345    599.000000
346    145.000000
347    502.881295
348    502.881295
349    502.881295
350    502.881295
351    502.881295
352    350.000000
353    502.881295
354    327.000000
355    661.000000
356    634.000000
357    971.000000
358    574.000000
359    502.881295
360    387.000000
361     78.000000
362    366.000000
363    667.000000
364    760.000000
365    506.000000
366    502.881295
367    411.000000
368    249.000000
369    905.000000
370    237.000000
371    340.000000
372    335.000000
373    502.881295
374    337.000000
375    912.000000
376    502.881295
377    560.000000
378    502.881295
379    346.000000
380    693.000000
381    454.000000
382    502.881295
383    797.000000
384    922.000000
385    167.000000
386    502.881295
387    620.000000
388    502.881295
389    940.000000
390    516.000000
391    875.000000
392    874.000000
393    502.881295
394    502.881295
395    564.000000
396    502.881295
397     63.000000
398    570.000000
399    502.881295

In [ ]:
# replace column_3 with mode
mod=df2["Column_3"].mode()
print(mod)
df2["Column_3"].fillna(mod,inplace=True)
print(df2["Column_3"].to_string())

0    472.323024
Name: Column_3, dtype: float64
0       829.000000
1       472.323024
2       533.000000
3       792.000000
4       145.000000
5       306.000000
6       705.000000
7       472.323024
8       555.000000
9       971.000000
10      472.323024
11      164.000000
12     1000.000000
13      472.323024
14       34.000000
15      197.000000
16      396.000000
17      341.000000
18      472.323024
19       17.000000
20      472.323024
21      472.323024
22      678.000000
23      115.000000
24       36.000000
25       56.000000
26      472.323024
27      384.000000
28      923.000000
29      283.000000
30      472.323024
31      738.000000
32      831.000000
33      472.323024
34      622.000000
35      438.000000
36       33.000000
37      548.000000
38      803.000000
39      863.000000
40      551.000000
41      356.000000
42       16.000000
43      446.000000
44      256.000000
45       91.000000
46      472.323024
47      756.000000
48      472.323024
49      119.000000
50      472.323024
51      965.000000
52      397.000000
53      127.000000
54      124.000000
55      472.323024
56      472.323024
57      162.000000
58      196.000000
59      162.000000
60      506.000000
61      166.000000
62      194.000000
63      277.000000
64      131.000000
65      250.000000
66      556.000000
67      472.323024
68      952.000000
69      472.323024
70      310.000000
71      295.000000
72      472.323024
73      363.000000
74      472.323024
75      868.000000
76      472.323024
77      800.000000
78      328.000000
79      652.000000
80      903.000000
81       39.000000
82       53.000000
83      472.323024
84      197.000000
85      997.000000
86      180.000000
87       47.000000
88       88.000000
89      472.323024
90      472.323024
91       41.000000
92      167.000000
93      472.323024
94      472.323024
95      805.000000
96      472.323024
97      472.323024
98       72.000000
99      449.000000
100     558.000000
101     920.000000
102     472.323024
103     631.000000
104     472.323024
105     665.000000
106     472.323024
107     533.000000
108     194.000000
109     915.000000
110     175.000000
111     298.000000
112     422.000000
113     472.323024
114     801.000000
115     472.323024
116     829.000000
117     472.323024
118      73.000000
119     472.323024
120      78.000000
121     999.000000
122     360.000000
123     223.000000
124     212.000000
125     772.000000
126     814.000000
127     469.000000
128     767.000000
129     195.000000
130     472.323024
131      25.000000
132     218.000000
133     878.000000
134     852.000000
135     620.000000
136     138.000000
137     772.000000
138      54.000000
139     690.000000
140      40.000000
141     745.000000
142     980.000000
143     982.000000
144     195.000000
145     190.000000
146     681.000000
147     559.000000
148     472.323024
149     472.323024
150     925.000000
151     233.000000
152     888.000000
153     565.000000
154     472.323024
155     472.323024
156     238.000000
157     723.000000
158     722.000000
159     472.323024
160     889.000000
161     753.000000
162     483.000000
163     646.000000
164     336.000000
165     118.000000
166     523.000000
167     472.323024
168     235.000000
169     928.000000
170     472.323024
171     161.000000
172     739.000000
173      51.000000
174     472.323024
175     472.323024
176     472.323024
177     658.000000
178     472.323024
179     938.000000
180     545.000000
181     472.323024
182     814.000000
183     472.323024
184     766.000000
185     157.000000
186     472.323024
187      35.000000
188     472.323024
189     663.000000
190     821.000000
191     472.323024
192     472.323024
193     818.000000
194     700.000000
195     441.000000
196     173.000000
197     787.000000
198     472.323024
199      89.000000
200     226.000000
201     801.000000
202     472.323024
203     472.323024
204     722.000000
205     958.000000
206     316.000000
207     340.000000
208     875.000000
209     591.000000
210     657.000000
211     867.000000
212     970.000000
213     472.323024
214      49.000000
215      46.000000
216     662.000000
217     982.000000
218     588.000000
219     358.000000
220     839.000000
221     443.000000
222      56.000000
223      11.000000
224     225.000000
225     477.000000
226     204.000000
227      21.000000
228     472.323024
229     183.000000
230     175.000000
231     849.000000
232     472.323024
233     472.323024
234     342.000000
235     971.000000
236      94.000000
237      40.000000
238     311.000000
239     359.000000
240     472.323024
241     257.000000
242     380.000000
243     466.000000
244     472.323024
245     472.323024
246     359.000000
247      38.000000
248       1.000000
249     472.323024
250     283.000000
251     472.323024
252     472.323024
253     194.000000
254     527.000000
255     184.000000
256     280.000000
257     173.000000
258     460.000000
259     472.000000
260     382.000000
261     194.000000
262     988.000000
263      62.000000
264     472.323024
265     472.323024
266     847.000000
267     472.323024
268     472.323024
269     909.000000
270     342.000000
271      90.000000
272     472.323024
273     326.000000
274     472.323024
275     472.323024
276     325.000000
277     855.000000
278     960.000000
279     790.000000
280     757.000000
281     992.000000
282     472.323024
283     760.000000
284     472.323024
285     265.000000
286     472.323024
287     893.000000
288     472.323024
289     234.000000
290     472.323024
291       5.000000
292     472.323024
293     806.000000
294     876.000000
295     472.000000
296     580.000000
297     472.323024
298     514.000000
299     917.000000
300     169.000000
301     321.000000
302     482.000000
303     709.000000
304     472.323024
305     801.000000
306     827.000000
307     210.000000
308     132.000000
309     472.323024
310      42.000000
311     472.323024
312     472.323024
313     665.000000
314     804.000000
315     472.323024
316     230.000000
317     220.000000
318     151.000000
319     876.000000
320      48.000000
321     733.000000
322     562.000000
323     472.323024
324     472.323024
325     498.000000
326      60.000000
327     879.000000
328     984.000000
329      59.000000
330      53.000000
331     906.000000
332     472.323024
333     472.323024
334     472.323024
335     490.000000
336      93.000000
337     472.323024
338     472.323024
339     472.323024
340      12.000000
341     822.000000
342     472.323024
343     472.323024
344     472.323024
345     472.323024
346     124.000000
347     472.323024
348     782.000000
349     472.323024
350     542.000000
351     593.000000
352     212.000000
353     967.000000
354     472.323024
355     517.000000
356     991.000000
357      11.000000
358     533.000000
359     426.000000
360     709.000000
361     472.323024
362     754.000000
363     450.000000
364     123.000000
365     905.000000
366     758.000000
367     472.323024
368     159.000000
369     268.000000
370     757.000000
371     472.323024
372     472.323024
373     411.000000
374     472.323024
375     737.000000
376     517.000000
377     472.323024
378     419.000000
379     622.000000
380     141.000000
381     472.323024
382     470.000000
383     472.323024
384     787.000000
385     194.000000
386     665.000000
387     472.323024
388      78.000000
389     472.323024
390     303.000000
391     453.000000
392     739.000000
393     559.000000
394     689.000000
395      99.000000
396     863.000000
397     813.000000
398     647.000000
399     169.000000

In [ ]:
their_mean=df2[["Column_4","Column_5","Column_6"]].mean()
print(their_mean)

Column_4    503.444043
Column_5    489.646617
Column_6    508.173145
dtype: float64

In [ ]:
df2[["Column_4","Column_5","Column_6"]].fillna(their_mean,inplace=True)
print(df2.to_string())

       Column_1    Column_2     Column_3    Column_4     Column_5    Column_6
0    688.000000  764.000000   829.000000  669.000000   489.646617  995.000000
1    883.000000  502.881295   472.323024  317.000000   906.000000  508.173145
2    489.361404  519.000000   533.000000  503.444043   362.000000  220.000000
3    223.000000  502.881295   792.000000  503.444043   329.000000  379.000000
4    780.000000    5.000000   145.000000  146.000000   109.000000  828.000000
5    489.361404  919.000000   306.000000  149.000000   478.000000  508.173145
6    643.000000  981.000000   705.000000  503.444043   546.000000  584.000000
7    315.000000  408.000000   472.323024  503.444043   489.646617  366.000000
8    165.000000  223.000000   555.000000  190.000000   358.000000  748.000000
9    489.361404  522.000000   971.000000  337.000000   599.000000  669.000000
10   541.000000  502.881295   472.323024  771.000000   489.646617  437.000000
11   489.361404  422.000000   164.000000  684.000000   164.000000  508.173145
12    48.000000  664.000000  1000.000000  444.000000   489.646617  793.000000
13   804.000000  983.000000   472.323024  503.444043   489.646617  508.173145
14   656.000000  502.881295    34.000000   74.000000   776.000000  508.173145
15   489.361404  392.000000   197.000000  503.444043   829.000000  776.000000
16   489.361404  502.881295   396.000000  943.000000   363.000000  237.000000
17   489.361404  502.881295   341.000000  691.000000   489.646617  310.000000
18   664.000000  283.000000   472.323024   34.000000   808.000000  143.000000
19   691.000000  529.000000    17.000000  503.444043   690.000000  606.000000
20   489.361404  502.881295   472.323024  866.000000   673.000000  508.173145
21   965.000000  787.000000   472.323024  690.000000   489.646617  508.173145
22   476.000000  563.000000   678.000000  633.000000   369.000000  883.000000
23   951.000000  502.881295   115.000000  750.000000   489.646617  788.000000
24   810.000000  776.000000    36.000000  605.000000   567.000000  375.000000
25   874.000000  754.000000    56.000000  503.444043   489.646617  508.173145
26   675.000000   77.000000   472.323024  158.000000   489.646617  927.000000
27   489.361404  158.000000   384.000000  729.000000   565.000000  508.173145
28   413.000000  502.881295   923.000000  291.000000   489.646617  800.000000
29   489.361404  225.000000   283.000000  503.444043   913.000000  168.000000
30   489.361404  502.881295   472.323024  920.000000   485.000000  911.000000
31   489.361404  502.881295   738.000000  503.444043    43.000000  496.000000
32   489.361404  861.000000   831.000000  503.444043    87.000000  136.000000
33   403.000000  502.881295   472.323024  503.444043   553.000000  508.173145
34   476.000000  917.000000   622.000000  885.000000    31.000000  744.000000
35    50.000000  502.881295   438.000000  264.000000   489.646617  508.173145
36   466.000000  502.881295    33.000000  503.444043   489.646617  508.173145
37   962.000000  502.881295   548.000000  503.444043   267.000000  864.000000
38   456.000000  202.000000   803.000000  828.000000   489.646617  508.173145
39   489.361404  502.881295   863.000000  997.000000   489.646617  279.000000
40   489.361404  502.881295   551.000000  453.000000   480.000000  462.000000
41   489.361404   32.000000   356.000000  937.000000   489.646617  870.000000
42   353.000000  516.000000    16.000000  708.000000   654.000000  838.000000
43   489.361404  502.881295   446.000000  835.000000   489.646617  880.000000
44   489.361404  533.000000   256.000000  331.000000   451.000000  508.173145
45   244.000000  502.881295    91.000000  503.444043   204.000000  987.000000
46   489.361404  940.000000   472.323024   79.000000    98.000000  735.000000
47   727.000000  537.000000   756.000000    4.000000   924.000000  749.000000
48    45.000000  502.881295   472.323024  385.000000   530.000000  800.000000
49   485.000000  687.000000   119.000000  796.000000   489.646617  216.000000
50   651.000000  442.000000   472.323024  227.000000   311.000000  424.000000
51   489.361404  474.000000   965.000000  116.000000   426.000000  208.000000
52   155.000000  100.000000   397.000000  480.000000   387.000000  508.173145
53   489.361404  502.881295   127.000000  198.000000   122.000000  508.173145
54   844.000000  213.000000   124.000000  919.000000   489.646617  595.000000
55   820.000000  502.881295   472.323024   70.000000   318.000000  268.000000
56   489.361404  244.000000   472.323024  403.000000   624.000000  373.000000
57   489.361404  767.000000   162.000000  503.444043    46.000000  770.000000
58   567.000000  998.000000   196.000000  503.444043    86.000000  799.000000
59   452.000000  502.881295   162.000000  826.000000   489.646617  508.173145
60   395.000000  502.881295   506.000000  103.000000    36.000000  149.000000
61   883.000000  502.881295   166.000000  942.000000   965.000000  903.000000
62   603.000000  502.881295   194.000000  503.444043   489.646617  813.000000
63   487.000000  502.881295   277.000000  558.000000   602.000000  508.173145
64   838.000000  911.000000   131.000000  823.000000   398.000000  101.000000
65   489.361404  493.000000   250.000000  503.444043   306.000000  508.173145
66   256.000000  785.000000   556.000000  503.444043   929.000000  816.000000
67   387.000000  502.881295   472.323024  439.000000   839.000000  508.173145
68   241.000000  537.000000   952.000000  432.000000   566.000000  508.173145
69   489.361404  951.000000   472.323024  503.444043   565.000000  847.000000
70   949.000000  980.000000   310.000000  804.000000   489.646617  765.000000
71   777.000000  519.000000   295.000000   19.000000   320.000000  508.173145
72   489.361404  928.000000   472.323024  303.000000   636.000000  832.000000
73   459.000000  507.000000   363.000000  688.000000   736.000000  835.000000
74   314.000000  676.000000   472.323024  199.000000   276.000000  508.173145
75   493.000000  502.881295   868.000000  893.000000   489.646617   47.000000
76   106.000000  502.881295   472.323024  988.000000   489.646617  508.173145
77    50.000000  502.881295   800.000000  503.444043   291.000000  104.000000
78    53.000000  502.881295   328.000000  503.444043   489.646617  383.000000
79   965.000000  718.000000   652.000000  503.444043   545.000000  180.000000
80   220.000000  502.881295   903.000000  503.444043   489.646617  508.173145
81   489.361404  546.000000    39.000000  503.444043   489.646617  839.000000
82   433.000000  424.000000    53.000000  531.000000   277.000000  235.000000
83   489.361404  198.000000   472.323024  995.000000    65.000000  508.173145
84   233.000000   37.000000   197.000000  943.000000   373.000000   18.000000
85   701.000000  755.000000   997.000000  503.444043   450.000000  508.173145
86   721.000000  330.000000   180.000000  384.000000   521.000000  485.000000
87   107.000000  194.000000    47.000000   15.000000   489.646617  873.000000
88     3.000000  830.000000    88.000000  455.000000   364.000000  667.000000
89    15.000000  353.000000   472.323024  826.000000   489.646617  372.000000
90   681.000000  129.000000   472.323024  503.444043   471.000000  116.000000
91   742.000000  427.000000    41.000000  503.444043   489.646617  524.000000
92    11.000000    8.000000   167.000000  830.000000   149.000000  619.000000
93   489.361404  703.000000   472.323024  741.000000   710.000000  836.000000
94   622.000000  356.000000   472.323024  831.000000   489.646617   50.000000
95   238.000000  502.881295   805.000000   99.000000   489.646617  994.000000
96   998.000000  502.881295   472.323024  503.444043   815.000000  215.000000
97   693.000000  152.000000   472.323024   83.000000   489.646617  877.000000
98   782.000000   24.000000    72.000000  524.000000   642.000000  281.000000
99   611.000000  307.000000   449.000000  503.444043   489.646617  146.000000
100  489.361404  278.000000   558.000000  934.000000   600.000000  210.000000
101  837.000000   63.000000   920.000000  503.444043   236.000000  421.000000
102  489.361404  482.000000   472.323024  130.000000   489.646617  783.000000
103  321.000000  502.881295   631.000000  216.000000   351.000000  292.000000
104  489.361404  168.000000   472.323024  503.444043   240.000000   72.000000
105  956.000000  242.000000   665.000000  229.000000   531.000000  508.173145
106  489.361404  502.881295   472.323024  503.444043   489.646617  508.173145
107   11.000000  309.000000   533.000000   73.000000   188.000000  226.000000
108  489.361404  502.881295   194.000000  503.444043   489.646617  306.000000
109  644.000000  572.000000   915.000000  338.000000   489.646617  508.173145
110  485.000000  502.881295   175.000000  727.000000   692.000000  382.000000
111  489.361404  193.000000   298.000000  503.444043   489.646617    8.000000
112  489.361404  120.000000   422.000000  970.000000   389.000000  192.000000
113  608.000000  118.000000   472.323024  791.000000   264.000000  508.173145
114   48.000000  522.000000   801.000000  231.000000   286.000000  164.000000
115  917.000000  838.000000   472.323024  135.000000   667.000000  300.000000
116  563.000000  695.000000   829.000000  503.444043   489.646617  508.173145
117  171.000000  854.000000   472.323024  962.000000   788.000000  508.173145
118  207.000000  502.881295    73.000000  654.000000   489.646617  904.000000
119  489.361404  502.881295   472.323024  492.000000   319.000000  209.000000
120  829.000000  503.000000    78.000000  503.444043   489.646617  542.000000
121  601.000000  651.000000   999.000000  416.000000   489.646617  824.000000
122  122.000000  445.000000   360.000000   80.000000   877.000000  811.000000
123  724.000000  865.000000   223.000000  834.000000   931.000000  669.000000
124  180.000000  151.000000   212.000000  503.444043   489.646617  648.000000
125  164.000000  942.000000   772.000000  503.444043   688.000000  508.173145
126  489.361404  746.000000   814.000000  503.444043   256.000000  779.000000
127  457.000000  871.000000   469.000000   64.000000   489.646617  305.000000
128  834.000000  768.000000   767.000000  105.000000   703.000000  508.173145
129  489.361404  504.000000   195.000000  503.444043   999.000000   84.000000
130  296.000000  909.000000   472.323024  503.444043   615.000000  779.000000
131  299.000000  502.881295    25.000000   36.000000   489.646617  822.000000
132  770.000000  994.000000   218.000000  367.000000    31.000000  508.173145
133  360.000000  299.000000   878.000000  561.000000   978.000000  508.173145
134  469.000000  502.881295   852.000000  380.000000   489.646617  551.000000
135  964.000000  879.000000   620.000000  591.000000   387.000000  508.173145
136  813.000000  502.881295   138.000000  564.000000   660.000000  508.173145
137  170.000000  782.000000   772.000000    9.000000   489.646617  819.000000
138  255.000000  502.881295    54.000000  759.000000   489.646617  829.000000
139   62.000000  650.000000   690.000000  875.000000   498.000000  508.173145
140  368.000000  156.000000    40.000000  684.000000   489.646617  508.173145
141  197.000000  502.881295   745.000000  503.444043   489.646617  508.173145
142  282.000000  911.000000   980.000000  425.000000   489.646617  448.000000
143  332.000000  440.000000   982.000000  214.000000   489.646617  350.000000
144  316.000000  502.881295   195.000000  540.000000   489.646617   56.000000
145  489.361404  150.000000   190.000000  503.444043   489.646617  508.173145
146  462.000000  507.000000   681.000000  503.444043  1000.000000  319.000000
147  752.000000  873.000000   559.000000  850.000000   864.000000  708.000000
148  489.361404  502.881295   472.323024  524.000000   366.000000  508.173145
149  370.000000  881.000000   472.323024  230.000000   418.000000  792.000000
150  216.000000  502.881295   925.000000  239.000000   526.000000  875.000000
151  333.000000  310.000000   233.000000  503.444043   235.000000  392.000000
152  489.361404  849.000000   888.000000  149.000000   489.646617  816.000000
153   60.000000  777.000000   565.000000  503.444043   489.646617  290.000000
154  425.000000  138.000000   472.323024  378.000000   489.646617  852.000000
155  489.361404  148.000000   472.323024  730.000000    76.000000  508.173145
156   30.000000  710.000000   238.000000  340.000000   300.000000  218.000000
157  489.361404  975.000000   723.000000  503.444043   489.646617  508.173145
158  361.000000  722.000000   722.000000  298.000000   143.000000  247.000000
159  489.361404  621.000000   472.323024  920.000000   489.646617  508.173145
160  698.000000  542.000000   889.000000  503.444043   607.000000  276.000000
161  489.361404  620.000000   753.000000  926.000000   222.000000   14.000000
162  512.000000  555.000000   483.000000  504.000000   239.000000  508.173145
163  489.361404  563.000000   646.000000  692.000000   489.646617  761.000000
164  200.000000  405.000000   336.000000  503.444043   489.646617  843.000000
165  364.000000  310.000000   118.000000  312.000000   561.000000  656.000000
166  489.361404  201.000000   523.000000  660.000000   748.000000  508.173145
167  305.000000  265.000000   472.323024  718.000000   318.000000  508.173145
168  959.000000  502.881295   235.000000  649.000000   909.000000  688.000000
169  893.000000  502.881295   928.000000  924.000000   840.000000   54.000000
170  489.361404  968.000000   472.323024  795.000000   489.646617  508.173145
171  300.000000  502.881295   161.000000  158.000000   650.000000  508.173145
172   96.000000  502.881295   739.000000   78.000000   217.000000  508.173145
173  196.000000  719.000000    51.000000  607.000000   489.646617  724.000000
174  610.000000   39.000000   472.323024  711.000000   406.000000  632.000000
175  460.000000  502.881295   472.323024  856.000000   887.000000  438.000000
176  849.000000  584.000000   472.323024  503.444043   489.646617  989.000000
177  312.000000  129.000000   658.000000  424.000000   325.000000    4.000000
178  489.361404  502.881295   472.323024  597.000000   489.646617  105.000000
179  489.361404  368.000000   938.000000  572.000000   360.000000  543.000000
180  489.361404  533.000000   545.000000  635.000000   489.646617  905.000000
181  347.000000   85.000000   472.323024  227.000000   967.000000  980.000000
182   78.000000  139.000000   814.000000  503.444043   982.000000  508.173145
183  638.000000  831.000000   472.323024  443.000000   489.646617   76.000000
184  621.000000  502.881295   766.000000  503.444043   760.000000  500.000000
185  450.000000  502.881295   157.000000  348.000000    87.000000  977.000000
186  375.000000  502.881295   472.323024  817.000000   489.646617  879.000000
187  749.000000  588.000000    35.000000  503.444043   489.646617  508.173145
188  489.361404  502.881295   472.323024  503.444043   489.646617  508.173145
189  972.000000  800.000000   663.000000  503.444043   489.646617  508.173145
190  344.000000  502.881295   821.000000  503.444043   957.000000  508.173145
191  427.000000  672.000000   472.323024  154.000000   638.000000  508.173145
192  344.000000  502.881295   472.323024  937.000000   432.000000  472.000000
193  489.361404  502.881295   818.000000  411.000000   489.646617  655.000000
194  600.000000  891.000000   700.000000  503.444043   198.000000  445.000000
195  258.000000  502.881295   441.000000  612.000000   489.646617  508.173145
196  807.000000  159.000000   173.000000  503.444043   734.000000  786.000000
197  766.000000  493.000000   787.000000  647.000000   489.646617  391.000000
198  236.000000  110.000000   472.323024  115.000000   489.646617  855.000000
199  872.000000  502.881295    89.000000  715.000000   814.000000  436.000000
200  704.000000  636.000000   226.000000  305.000000   134.000000  537.000000
201  711.000000   50.000000   801.000000   75.000000   644.000000   68.000000
202  302.000000  295.000000   472.323024  343.000000   130.000000  508.173145
203  489.361404  762.000000   472.323024  760.000000   387.000000  510.000000
204  958.000000  418.000000   722.000000  616.000000   331.000000  508.173145
205  112.000000  767.000000   958.000000  503.444043     1.000000  337.000000
206  145.000000  718.000000   316.000000  503.444043   489.646617  629.000000
207  607.000000  502.881295   340.000000  577.000000   905.000000  508.173145
208  489.361404  866.000000   875.000000  429.000000    10.000000  508.173145
209  651.000000  623.000000   591.000000   78.000000   495.000000  512.000000
210  869.000000  502.881295   657.000000  366.000000   852.000000  601.000000
211  931.000000  502.881295   867.000000   61.000000   175.000000  168.000000
212  197.000000  879.000000   970.000000  309.000000    98.000000  966.000000
213  489.361404  275.000000   472.323024  779.000000   197.000000  987.000000
214  489.361404  502.881295    49.000000  367.000000   582.000000  574.000000
215  905.000000  733.000000    46.000000  503.444043   489.646617  809.000000
216  779.000000  424.000000   662.000000  196.000000   489.646617  399.000000
217  292.000000  126.000000   982.000000  989.000000   938.000000  434.000000
218  704.000000  102.000000   588.000000  213.000000   789.000000  114.000000
219  649.000000  855.000000   358.000000  503.444043   325.000000  508.173145
220  374.000000   38.000000   839.000000  471.000000    88.000000  786.000000
221  584.000000   77.000000   443.000000  837.000000   345.000000  111.000000
222    4.000000  795.000000    56.000000  235.000000    25.000000  508.173145
223  489.361404  114.000000    11.000000  594.000000   489.646617  508.173145
224  302.000000  211.000000   225.000000  805.000000   587.000000    6.000000
225  863.000000   10.000000   477.000000  442.000000   113.000000  396.000000
226  366.000000  771.000000   204.000000  503.444043    57.000000  653.000000
227  782.000000  262.000000    21.000000  595.000000   489.646617  610.000000
228  247.000000  716.000000   472.323024  888.000000   489.646617  320.000000
229  502.000000  237.000000   183.000000  928.000000   242.000000  981.000000
230  424.000000  814.000000   175.000000  395.000000   361.000000  325.000000
231  244.000000  502.881295   849.000000  714.000000   694.000000  214.000000
232  901.000000  502.881295   472.323024   41.000000   543.000000  508.173145
233  945.000000  502.881295   472.323024  503.444043   489.646617   97.000000
234  726.000000  412.000000   342.000000  983.000000   462.000000  540.000000
235  157.000000  597.000000   971.000000  878.000000   356.000000  213.000000
236  283.000000  274.000000    94.000000    9.000000   489.646617  105.000000
237  489.361404  424.000000    40.000000  901.000000   831.000000   95.000000
238  840.000000  686.000000   311.000000  503.444043   489.646617  508.173145
239  489.361404  502.881295   359.000000  503.444043    47.000000  767.000000
240   95.000000  618.000000   472.323024  503.444043   369.000000  786.000000
241  489.361404  919.000000   257.000000  314.000000   473.000000  909.000000
242  205.000000  467.000000   380.000000  503.444043    37.000000    1.000000
243  881.000000  767.000000   466.000000  503.444043   489.646617  508.173145
244  489.361404  502.881295   472.323024  806.000000   331.000000  508.173145
245  489.361404   56.000000   472.323024  680.000000   489.646617  582.000000
246  954.000000  604.000000   359.000000  503.444043   489.646617   11.000000
247  211.000000  782.000000    38.000000  503.444043   474.000000  508.173145
248  489.361404  502.881295     1.000000  503.444043   489.646617  958.000000
249  383.000000  916.000000   472.323024  649.000000   489.646617  922.000000
250   34.000000  598.000000   283.000000  503.444043   948.000000  947.000000
251  838.000000  237.000000   472.323024  929.000000   489.646617  306.000000
252  370.000000  299.000000   472.323024  503.444043   838.000000  508.173145
253  201.000000  471.000000   194.000000  706.000000   803.000000  838.000000
254   25.000000  197.000000   527.000000  503.444043   707.000000  681.000000

<ipython-input-25-fae03d897bd4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[["Column_4","Column_5","Column_6"]].fillna(their_mean,inplace=True)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column_1  400 non-null    float64
 1   Column_2  400 non-null    float64
 2   Column_3  400 non-null    float64
 3   Column_4  400 non-null    float64
 4   Column_5  400 non-null    float64
 5   Column_6  400 non-null    float64
dtypes: float64(6)
memory usage: 18.9 KB

# cleaning Data in wrong format

# Fixing wrong format data

In [ ]:
df=pd.DataFrame({
    "date":["2022-03-14","01-02-2023","2020-04-13","3.4.2018","2020 4 1"]

})
print(df)

         date
0  2022-03-14
1  01-02-2023
2  2020-04-13
3    3.4.2018
4    2020 4 1

In [ ]:
df["date"]=pd.to_datetime(df["date"],format="mixed")
print(df)

        date
0 2022-03-14
1 2023-01-02
2 2020-04-13
3 2018-03-04
4 2020-04-01

#REmoving Wrong format Data

In [ ]:
import pandas as pd

In [ ]:
df1=pd.DataFrame({
    "date":["2022-03-14","01-02-2023","2020-04-13","","2020 4 1"]

})
print(df1)

         date
0  2022-03-14
1  01-02-2023
2  2020-04-13
3
4    2020 4 1

In [ ]:
df1["date"]=pd.to_datetime(df1["date"],format="mixed")
print(df1)

        date
0 2022-03-14
1 2023-01-02
2 2020-04-13
3        NaT
4 2020-04-01

In [ ]:
df1.dropna(subset=["date"],inplace=True)
print(df1)
#df1["date"].dropna(inplace=True)

        date
0 2022-03-14
1 2023-01-02
2 2020-04-13
4 2020-04-01

In [ ]:
df1

        date
0 2022-03-14
1 2023-01-02
2 2020-04-13
4 2020-04-01

# wrong Data

## Replacing wrong Data

In [ ]:
data={
    "name":["vishunu","kiran","abi","snan","yscn","anand","sxmil"],
    "age":[17,18,160,19,19,18,22],
    "salary":[25000,18000,30000,300000,22000,32000,15000]
}
df=pd.DataFrame(data,index=["a","b","c","d","e","f","g"])
df

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi  160   30000
d     snan   19  300000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   15000

In [ ]:
df.loc["d","salary"]=30000
df.loc["c","age"]=16

In [ ]:
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi   16   30000
d     snan   19   30000
e     yscn   19   22000
f    anand   18   30000
g    sxmil   22   15000

## if the DataSET is very big we can use a for loop

In [ ]:
# example for a for loo[p
x=[10,20,30,40,50,100,110,120]
y=100
for i in x:
  if i >= y:
    i=y
  print(i,end=" ")

10 20 30 40 50 100 100 100

In [ ]:
x=[10,20,30,40,50,100,110,120]
lst=[]
for i in x:
  if i>100:
    lst.append(100)
  else:
    lst.append(i)
print(lst)

[10, 20, 30, 40, 50, 100, 100, 100]

In [ ]:
data={
    "name":["vishunu","kiran","abi","snan","yscn","anand","sxmil"],
    "age":[17,18,160,19,19,18,22],
    "salary":[25000,18000,30000,300000,22000,32000,15000]
}
df=pd.DataFrame(data,index=["a","b","c","d","e","f","g"])
df

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi  160   30000
d     snan   19  300000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   15000

In [ ]:
for i in df.index:
  print(i)

a
b
c
d
e
f
g

In [ ]:
for i  in df.index:
  if df.loc[i,"salary"] > 50000:
    df.loc[i,"salary"] = 35000

In [ ]:
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi  160   30000
d     snan   19   35000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   15000

In [ ]:
for x in df.index:
  if df.loc[x,"age"] > 25:
    df.loc[x,"age"] = 20
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi   20   30000
d     snan   19   35000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   15000

In [ ]:
df.loc["g","salary"]=50000
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   18000
c      abi   20   30000
d     snan   19   35000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   50000

In [ ]:
for i in df.index:
  if df.loc[i,"salary"] <20000:
    df.loc[i,"salary"] = 45000
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   45000
c      abi   20   30000
d     snan   19   35000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   50000

In [ ]:
for i in df.index:
  if df.loc[i,"age"] >= 20:
    df.loc[i,"salary"] = 50000
print(df)

      name  age  salary
a  vishunu   17   25000
b    kiran   18   45000
c      abi   20   50000
d     snan   19   35000
e     yscn   19   22000
f    anand   18   32000
g    sxmil   22   50000

## remove the wrong data

In [ ]:
data={
    "name":["shifan","insaf","swalh","edwin","david"],
    "age":[18,19,20,17,21],
    "salary":[25000,30000,20000,34000,28000],
    "exp":[5,4,5,6,7]
}
df=pd.DataFrame(data)

In [ ]:
df

     name  age  salary  exp
0  shifan   18   25000    5
1   insaf   19   30000    4
2   swalh   20   20000    5
3   edwin   17   34000    6
4   david   21   28000    7

In [ ]:
df.drop(0,inplace=True)

In [ ]:
df

    name  salary  exp
1  insaf   30000    4
2  swalh   20000    5
3  edwin   34000    6
4  david   28000    7

In [ ]:
for x in df.index:
  if df.loc[x,"age"]>20:
    df.drop(x,inplace=True)
df

    name  age  salary  exp
1  insaf   19   30000    4
2  swalh   20   20000    5
3  edwin   17   34000    6

# duplicates

## remove duplicates

In [ ]:
import pandas as pd

In [ ]:
dup=[[10,2,43],[11,5,15],[10,2,67],[10,2,43],[34,70,5],[23,45,32],[10,2,43]]
df=pd.DataFrame(dup)
print(df)

    0   1   2
0  10   2  43
1  11   5  15
2  10   2  67
3  10   2  43
4  34  70   5
5  23  45  32
6  10   2  43

In [ ]:
print(df.duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

    0   1   2
0  10   2  43
1  11   5  15
2  10   2  67
4  34  70   5
5  23  45  32

In [ ]:
data={
    "equipment":["fan","Ac","board","fan"],
    "price":[2500,36000,150000,2500],
    "quantity":[2,2,1,2]
}

xdf=pd.DataFrame(data)

In [ ]:
print(xdf.duplicated())

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
xdf.drop_duplicates(inplace=True)
print(xdf)

  equipment   price  quantity
0       fan    2500         2
1        Ac   36000         2
2     board  150000         1